---
- name: "Install IPA servers"
  hosts: ipaserver
  become: true
  roles:
  - role: ipaserver
    state: present

- name: "Install IPA clients"
  hosts: ipaclients
  become: true
  roles:
  - role: ipaclient
    state: present